SUPABASE_URL = "https://vitoohbkhesyhwjkejyj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdG9vaGJraGVzeWh3amtlanlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMDYxNzIsImV4cCI6MjA1MTU4MjE3Mn0.v8_Y9AlTBYJhxDfvHiyF2EoZAsdHUXWLQqfSDC0Tjvk"
# Keep your other secrets
GROQ_API_KEY = "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"
SERPAPI_KEY = "5a1c9bfb903e6b0224a8d31b26470a45c536e5d18cf7c1ae10453cdb5b156de4"
USER_AGENT = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
NEWSAPI_KEY = "0f9493bcb3b24ed49e5afb56031dfec8"
